config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'home/index'

  resources :users
  resources :books
  resources :searches

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        else
            all
        end
    end
end

app/models/search.rb
class Search < ApplicationRecord

    def search_books

        books = Book.all

        books = books.where(["name LIKE ?", "%#{name}%"]) if name.present?
        books = books.where(["author LIKE ?", "%#{author}%"]) if author.present?
        books = books.where(["isbn LIKE ?", "%#{isbn}%"]) if isbn.present?

        return books

    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_divise_params, if: :devise_controller?

      def configure_divise_params
          devise_parameter_sanitizer.permit(:sign_up) do |user|
              user.permit(:name, :address, :phone, :city, :email, :password, :password_confirmation)
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @book = Book.search(params[:search])
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)

        if @book.save
            redirect_to @book
        else
            render 'new'
        end
    end

    def show
        @book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])

        if @book.update(book_params)
            redirect_to @book
        else
            render 'edit'
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    private

    def book_params
        params.require(:book).permit(:isbn, :name, :author, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def new
        @search = Search.new
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def show
        @search = Search.find(params[:id])
    end

    private
    def search_params
        params.require(:search).permit(:name, :author, :isbn)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_instances_helper.rb
module BookInstancesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_with(model: @book) do |form| %>
    <div class="field form-group col-3">
   <%= form.label :name%><br>
   <%= form.text_field :name, class: "form-control" %>
   </div>

     <div class="field form-group col-3">
    <%= form.label :isbn%><br>
    <%= form.text_field :isbn, class: "form-control" %>
</div>

     <div class="field form-group col-3">
    <%= form.label :author%><br>
    <%= form.text_field :author, class: "form-control" %>
</div>

     <div class="field form-group col-3">
   <%= form.label :description %><br>
   <%= form.text_field :description, class: "form-control" %>
   </div>

 <p>
   <%= form.submit %>
 </p>


<% end %>

<%= link_to 'Back', books_path, class: "btn btn-info" %>

app/views/books/index.html.erb
<h1 class="display-4">My Books</h1>
    <div class="field form-group col-4">
    <%= form_tag books_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder:"Which book are you looking for?" %>
        <%= submit_tag "Search", class: "boton btn btn-primary" %>
    <% end %>
    <%= link_to 'Advanced Search', new_search_path, class: "btn btn-primary" %>
    </div>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Name</th>
      <th>Author</th>
    </tr>
  </thead>
  <% @book.each do |book| %>
  <tbody>
    <tr>
      <td><%= book.isbn%></td>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= link_to 'show', book_path(book), class: "btn btn-primary " %></td>
      <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-warning text-white" %></td>
      <td><%= link_to 'destroy', book_path(book), class: "btn btn-danger",
             method: :delete,
             data: {confirm: 'Are you sure?'} %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<%= link_to 'New Book', new_book_path, class: "btn btn-primary " %>
<%= link_to 'My Profile', user_path(current_user), class: "btn btn-primary " %>

<%= link_to 'Back', new_user_session_path, class: "btn btn-info " %>

app/views/books/new.html.erb
<h1 class="display-4"> New book </h1>
<%= form_for :book, url: books_path, method: :post do |f|%>

<% if @book.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
    </h2>
    <ul>
        <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="field form-group col-3">
    <%= f.label :name %><br>
    <%=  f.text_field :name, class: "form-control" %><br>
</div>
<div class="field form-group col-3">
    <%= f.label :isbn %><br>
    <%=  f.text_field :isbn, class: "form-control" %><br>
</div>
<div class="field form-group col-3">
    <%= f.label :author %><br>
    <%=  f.text_field :author, class: "form-control" %><br>
</div>
<div class="field form-group col-3">
    <%= f.label :description %><br>
    <%=  f.text_area :description, class: "form-control" %><br>
</div>
<%= f.submit 'create', class:"btn btn-primary"%>
<% end %>
<%= link_to 'my profile', user_path(current_user), class:"btn btn-primary" %>
<%= link_to 'Back', new_user_session_path, class:"btn btn-info" %>

app/views/books/search.html.erb
<h1>All Books</h1>
<%= link_to 'sign_out', new_user_session_path %>
<%= link_to 'new_book', new_book_path %>


<%= form_tag books_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search"%>
  </p>
<% end %>


<table>
  <tr>
    <th>Books</th>
  </tr>

  <% @book.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= link_to 'see book', book_path(book) %></td>
      <td><%= link_to 'delete', book_path(book),
             method: :delete,
             data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', new_user_session_path %>

app/views/books/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
</p>

<p>
    <strong>Author:</strong>
    <%= @book.author %>
</p>

<p>
  <strong>description:</strong>
  <%= @book.description%>
</p>

<%= link_to 'Back', books_path %>
<%= link_to 'Edit', edit_book_path %>

app/views/home/index.html.erb
<% if user_signed_in? %>
<h3 class="text display-4 col-6">"Literature is the art of the word". <br> <strong>Manuel Gayol Fernández</strong> </h3>
<h1 class="display-2 mt-5">Welcome <%= current_user.name %></h1>
<%= link_to 'New Book', new_book_path, class: "btn btn-primary " %>
<%= link_to 'My Books', books_path, class: "btn btn-primary" %>
<%= link_to 'My Profile', user_path(current_user), class: "btn btn-primary" %>
<%= link_to 'Edit profile ', edit_user_registration_path, class: "btn btn-primary" %>

<% else %>
<h3 class="text display-4 col-6">"The writing is the paint of the voice". <br> <strong>Voltaire.</strong></h3>
<h1 class="display-2 mt-5">Bye friend.</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Sessions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <header>
        <nav class="navbar nav-inverse bg-primary d-flex justify-content-end">
            <a class="navbar-brand text-white mr-auto p-2" href="#">Library Books</a>
            <!-- Navbar content -->
            <ul class="nav">
                <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign in', new_user_session_path %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path %>
                </li>
                <% end %>
            </ul>
        </nav>
    </header>


    <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
    </div>
</body>
</html>

app/views/searches/new.html.erb
<h1 class="display-4"> Custom Search </h1>
<%= form_for @search, html: {class: "pure-form"} do |f| %>

<div class="field form-group col-3">
    <%= f.label :name %><br>
    <%=  f.text_field :name, class: "form-control" %><br>
</div>
<div class="field form-group col-3">
    <%= f.label :isbn %><br>
    <%=  f.text_field :isbn, class: "form-control" %><br>
</div>
<div class="field form-group col-3">
    <%= f.label :author %><br>
    <%=  f.text_field :author, class: "form-control" %><br>
</div>
<div class="actions"><%= f.submit 'search', class:"btn btn-primary"%></div>
<% end %>

<%= link_to 'Back', books_path, class: "btn btn-primary" %>

app/views/searches/show.html.erb
<h1 class="display-4">Search Result</h1>

<% if @search.search_books.empty? %>
<p>No Records Found</p>
<% else %>

<br>
<table class="table table-inverse">
    <thead>
        <tr>
            <th>Name</th>
            <th>Author</th>
            <th>Isbn</th>
        </tr>
    </thead>
    <% @search.search_books.each do |c| %>
    <tbody>
        <tr>
            <th><%= c.name %></th>
            <th><%= c.author %></th>
            <th><%= c.isbn %></th>
        </tr>
    </tbody>
</table>

<% end %>
<% end %>

<%= link_to 'Back', new_search_path, class:"btn btn-primary" %>

app/views/users/show.html.erb
<h1 class="text-center display-4 col-4 ml-4">My Profile</h1>

<div class="card text-center ml-5" style="width: 20rem;">
  <img class="card-img-top" src="http://focuslabllc.com/assets/team/WEB-AlexSailer.jpg")>
  <div class="card-block">
    <h4 class="card-title pt-2">Name:<strong><%= current_user.name %></strong></h4>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">City:<strong><%= current_user.city %></strong></li>
    <li class="list-group-item">Adress:<strong><%= current_user.address %></strong></li>
    <li class="list-group-item">Phone:<strong><%= current_user.phone %></strong></li>
    <li class="list-group-item"><%= link_to 'new_book', new_book_path, class: "btn btn-primary btn-block" %></li>
    <li class="list-group-item"><%= link_to 'My Books', books_path, class: "btn btn-primary btn-block" %></li>
    <li class="list-group-item"><%= link_to 'Edit profile ', edit_user_registration_path, class: "btn btn-primary btn-block" %></li>
    <li class="list-group-item mb-5"><%= link_to 'Back', new_user_session_path, class:"btn btn-info btn-block" %></li>
  </ul>



</div>


<!-- <%= form_tag books_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search"%>
  </p>
<% end %> -->